# Generated by Django 5.2.7 on 2025-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='selected_indexes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
