# Generated by Django 5.2.7 on 2025-12-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_indexes',
        ),
    ]
