# Generated by Codex on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_studentanswer_selected_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentanswer",
            name="selected_indexes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
