# Generated by Django 6.0.3 on 2026-04-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inscripcion_status_activation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de inscripcion', 'verbose_name_plural': 'Solicitudes de inscripcion'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Registro de plataforma', 'verbose_name_plural': 'Registros de plataforma'},
        ),
    ]
