# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_inscripcion_options_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="source_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_snapshots",
                to="core.question",
            ),
        ),
    ]
