# Generated by Codex on 2026-05-07

from django.db import migrations


def backfill_source_question(apps, schema_editor):
    Question = apps.get_model("core", "Question")
    ExamQuestion = apps.get_model("core", "ExamQuestion")

    question_by_text = {}
    duplicate_texts = set()
    for question in Question.objects.only("id", "text").iterator():
        key = (question.text or "").strip()
        if not key:
            continue
        if key in question_by_text:
            duplicate_texts.add(key)
            continue
        question_by_text[key] = question.id

    for text in duplicate_texts:
        question_by_text.pop(text, None)

    batch = []
    for exam_question in (
        ExamQuestion.objects.filter(source_question__isnull=True)
        .only("id", "question_text", "source_question")
        .iterator()
    ):
        source_question_id = question_by_text.get((exam_question.question_text or "").strip())
        if not source_question_id:
            continue
        exam_question.source_question_id = source_question_id
        batch.append(exam_question)
        if len(batch) >= 500:
            ExamQuestion.objects.bulk_update(batch, ["source_question"])
            batch = []

    if batch:
        ExamQuestion.objects.bulk_update(batch, ["source_question"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_examquestion_source_question"),
    ]

    operations = [
        migrations.RunPython(backfill_source_question, migrations.RunPython.noop),
    ]
