# Generated by Django 6.0.3 on 2026-06-20 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_activationcode_used_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.localdate)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('curso', models.CharField(blank=True, max_length=120)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor_pagado', models.PositiveIntegerField(default=0)),
                ('forma_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('MIXTO', 'Mixto'), ('OTRO', 'Otro')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha_alumno', to='core.inscripcion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de alumno',
                'verbose_name_plural': 'Fichas de alumnos',
                'ordering': ['-fecha_inscripcion', '-numero_ficha'],
            },
        ),
    ]
