# Generated by Django 6.0.3 on 2026-06-25 02:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def tipo_desde_concepto(concepto):
    normalized = (concepto or '').casefold()
    if 'extra' in normalized:
        return 'CLASE_EXTRA'
    if 'sico' in normalized or 'psico' in normalized or 'ensayo' in normalized:
        return 'ENSAYO_SICOTECNICO'
    if 'simulador' in normalized:
        return 'SIMULADOR'
    if 'libro' in normalized:
        return 'LIBRO'
    if 'abono' in normalized:
        return 'ABONO'
    if normalized:
        return 'CURSO'
    return 'OTRO'


def crear_movimientos_iniciales(apps, schema_editor):
    FichaAlumno = apps.get_model('core', 'FichaAlumno')
    FichaMovimiento = apps.get_model('core', 'FichaMovimiento')
    movimientos = []
    for ficha in FichaAlumno.objects.all().iterator():
        concepto = ficha.curso or 'Pago inicial'
        movimientos.append(
            FichaMovimiento(
                ficha_id=ficha.id,
                fecha=ficha.fecha_inscripcion,
                tipo=tipo_desde_concepto(concepto),
                concepto=concepto,
                monto=ficha.valor_pagado,
                es_inicial=True,
                forma_pago=ficha.forma_pago,
                observaciones='Movimiento inicial generado desde la ficha.',
            )
        )
    FichaMovimiento.objects.bulk_create(movimientos, batch_size=500)


def eliminar_movimientos_iniciales(apps, schema_editor):
    FichaMovimiento = apps.get_model('core', 'FichaMovimiento')
    FichaMovimiento.objects.filter(es_inicial=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fichaalumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('CLASE_EXTRA', 'Clase extra'), ('ENSAYO_SICOTECNICO', 'Ensayo sicotecnico'), ('SIMULADOR', 'Simulador'), ('LIBRO', 'Libro'), ('ABONO', 'Abono'), ('OTRO', 'Otro')], default='CURSO', max_length=24)),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.PositiveIntegerField(default=0)),
                ('es_inicial', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('MIXTO', 'Mixto'), ('OTRO', 'Otro')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.fichaalumno')),
            ],
            options={
                'verbose_name': 'Movimiento de ficha',
                'verbose_name_plural': 'Movimientos de fichas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.RunPython(crear_movimientos_iniciales, eliminar_movimientos_iniciales),
    ]
