# Generated by Django 6.0.3 on 2026-06-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fichamovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='direccion',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
