# Generated by Django 6.0.3 on 2026-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_activationcode_sent_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='rut',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
