# Generated by Django 6.0.3 on 2026-06-01 01:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=12)),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('current_odometer', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odo_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='OdometerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('odometer', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('FUEL', 'Carga de combustible'), ('MAINTENANCE', 'Mantenimiento')], default='MANUAL', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to='odo.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DONE', 'Realizado'), ('OVERDUE', 'Vencido'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='odo.vehicle')),
            ],
            options={
                'ordering': ['status', 'due_date', 'due_odometer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('odometer', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='odo.maintenanceschedule')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='odo.vehicle')),
            ],
            options={
                'verbose_name': 'Mantenimiento realizado',
                'verbose_name_plural': 'Mantenimientos realizados',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DATE', 'Fecha'), ('ODOMETER', 'Kilometraje')], max_length=12)),
                ('severity', models.CharField(choices=[('WARNING', 'Preventiva'), ('CRITICAL', 'Critica')], max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('SEEN', 'Vista'), ('DISMISSED', 'Descartada')], default='OPEN', max_length=12)),
                ('threshold_value', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='odo.maintenanceschedule')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='odo.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('odometer', models.PositiveIntegerField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='odo.vehicle')),
            ],
            options={
                'verbose_name': 'Carga de combustible',
                'verbose_name_plural': 'Cargas de combustible',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('owner', 'plate'), name='unique_odo_vehicle_plate_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='maintenancealert',
            constraint=models.UniqueConstraint(fields=('schedule', 'kind', 'threshold_value', 'severity'), name='unique_odo_alert_per_schedule_threshold'),
        ),
    ]
