# Generated by Django 6.0.3 on 2026-06-14 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def consolidate_vehicle_plates(apps, schema_editor):
    Vehicle = apps.get_model("odo", "Vehicle")
    VehicleAccess = apps.get_model("odo", "VehicleAccess")
    FuelEntry = apps.get_model("odo", "FuelEntry")
    MaintenanceAlert = apps.get_model("odo", "MaintenanceAlert")
    MaintenanceRecord = apps.get_model("odo", "MaintenanceRecord")
    MaintenanceSchedule = apps.get_model("odo", "MaintenanceSchedule")
    OdometerReading = apps.get_model("odo", "OdometerReading")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    vehicles_by_plate = {}
    for vehicle in Vehicle.objects.order_by("id"):
        normalized_plate = (vehicle.plate or "").strip().upper()
        if normalized_plate != vehicle.plate:
            vehicle.plate = normalized_plate
            vehicle.save(update_fields=["plate"])
        vehicles_by_plate.setdefault(normalized_plate, []).append(vehicle)

    for plate, vehicles in vehicles_by_plate.items():
        if not plate or not vehicles:
            continue

        canonical = vehicles[0]
        owner_ids = {canonical.owner_id}
        max_odometer = canonical.current_odometer

        for duplicate in vehicles[1:]:
            owner_ids.add(duplicate.owner_id)
            max_odometer = max(max_odometer, duplicate.current_odometer)
            FuelEntry.objects.filter(vehicle=duplicate).update(vehicle=canonical)
            MaintenanceAlert.objects.filter(vehicle=duplicate).update(vehicle=canonical)
            MaintenanceRecord.objects.filter(vehicle=duplicate).update(vehicle=canonical)
            MaintenanceSchedule.objects.filter(vehicle=duplicate).update(vehicle=canonical)
            OdometerReading.objects.filter(vehicle=duplicate).update(vehicle=canonical)
            duplicate.delete()

        if canonical.current_odometer != max_odometer:
            canonical.current_odometer = max_odometer
            canonical.save(update_fields=["current_odometer"])

        staff_owner_ids = User.objects.filter(
            id__in=[owner_id for owner_id in owner_ids if owner_id],
            is_staff=True,
        ).values_list("id", flat=True)
        for user_id in staff_owner_ids:
            VehicleAccess.objects.get_or_create(vehicle_id=canonical.id, user_id=user_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('odo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acceso ODO por patente',
                'verbose_name_plural': 'Accesos ODO por patente',
                'ordering': ['vehicle__plate', 'user__email', 'user__username'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_odo_vehicle_plate_per_owner',
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odo_fuel_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odo_maintenance_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odo_readings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='alias',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vehicleaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odo_vehicle_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleaccess',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to='odo.vehicle'),
        ),
        migrations.RunPython(consolidate_vehicle_plates, noop_reverse),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('plate',), name='unique_odo_vehicle_plate'),
        ),
        migrations.AddConstraint(
            model_name='vehicleaccess',
            constraint=models.UniqueConstraint(fields=('vehicle', 'user'), name='unique_odo_vehicle_access_per_user'),
        ),
    ]
