# Generated by Django 6.0.3 on 2026-06-14 02:03

import odo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odo', '0002_vehicleaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, validators=[odo.models.validate_plate]),
        ),
    ]
