# Generated by Django 6.0.3 on 2026-06-29 05:28

import django.db.models.deletion
import odo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odo', '0003_alter_vehicle_plate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TECHNICAL_INSPECTION', 'Revision tecnica'), ('EMISSIONS', 'Gases'), ('CIRCULATION_PERMIT', 'Permiso circulacion'), ('SOAP', 'SOAP'), ('INSURANCE', 'Seguro automotriz'), ('DRIVER_LICENSE', 'Licencia conductor'), ('REGISTRATION', 'Padron'), ('OTHER', 'Otro')], max_length=32)),
                ('file', models.FileField(upload_to=odo.models.vehicle_document_upload_path)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odo_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='odo.vehicle')),
            ],
            options={
                'verbose_name': 'Documento de vehiculo',
                'verbose_name_plural': 'Documentos de vehiculos',
                'ordering': ['expires_at', 'vehicle__plate', 'document_type'],
            },
        ),
    ]
