# Generated by Django 6.0.3 on 2026-06-20 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_key', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ficha', models.PositiveIntegerField()),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('course_kind', models.CharField(choices=[('12_MODULOS', '12 modulos'), ('10_MODULOS', '10 modulos'), ('8_HORAS', '8 horas'), ('6_HORAS', '6 horas'), ('OTRO', 'Otro')], default='12_MODULOS', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_driving_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time', 'ficha', 'lesson_number'],
                'constraints': [models.UniqueConstraint(fields=('date', 'slot_key'), name='unique_driving_lesson_by_date_slot')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('DAY', 'Dia completo'), ('SLOT', 'Horario')], max_length=8)),
                ('slot_key', models.CharField(blank=True, max_length=16)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'scope', 'slot_key'],
                'constraints': [models.UniqueConstraint(fields=('date', 'scope', 'slot_key'), name='unique_schedule_block_by_date_scope_slot')],
            },
        ),
    ]
