# Generated by Django 6.0.3 on 2026-06-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0001_initial'),
        ('core', '0019_fichaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglesson',
            name='ficha_alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_practicas', to='core.fichaalumno'),
        ),
    ]
