# Generated by Django 6.0.3 on 2026-06-21 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0002_drivinglesson_ficha_alumno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglesson',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendada'), ('COMPLETED', 'Ejecutada'), ('ABSENT', 'Ausente alumno'), ('SCHOOL_SUSPENDED', 'Suspendida por escuela'), ('STUDENT_RESCHEDULED', 'Reagendada por alumno')], default='SCHEDULED', max_length=24),
        ),
        migrations.CreateModel(
            name='ScheduleOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('DAY', 'Dia completo'), ('SLOT', 'Horario')], max_length=8)),
                ('slot_key', models.CharField(blank=True, max_length=16)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_openings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'scope', 'slot_key'],
                'constraints': [models.UniqueConstraint(fields=('date', 'scope', 'slot_key'), name='unique_schedule_opening_by_date_scope_slot')],
            },
        ),
    ]
