# Generated by Django 6.0.3 on 2026-06-22 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_default_resource(apps, schema_editor):
    ScheduleResource = apps.get_model('agendamiento', 'ScheduleResource')
    DrivingLesson = apps.get_model('agendamiento', 'DrivingLesson')
    ScheduleBlock = apps.get_model('agendamiento', 'ScheduleBlock')
    ScheduleOpening = apps.get_model('agendamiento', 'ScheduleOpening')
    resource, _ = ScheduleResource.objects.get_or_create(
        name='Instructor 1 / Auto 1',
        defaults={
            'instructor': 'Instructor 1',
            'vehicle': 'Auto 1',
            'sort_order': 1,
            'is_active': True,
        },
    )
    DrivingLesson.objects.filter(resource__isnull=True).update(resource=resource)
    ScheduleBlock.objects.filter(resource__isnull=True).update(resource=resource)
    ScheduleOpening.objects.filter(resource__isnull=True).update(resource=resource)


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0003_drivinglesson_status_scheduleopening'),
        ('core', '0019_fichaalumno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('instructor', models.CharField(blank=True, max_length=120)),
                ('vehicle', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Recurso de agendamiento',
                'verbose_name_plural': 'Recursos de agendamiento',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='drivinglesson',
            name='unique_driving_lesson_by_date_slot',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleblock',
            name='unique_schedule_block_by_date_scope_slot',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleopening',
            name='unique_schedule_opening_by_date_scope_slot',
        ),
        migrations.AddField(
            model_name='drivinglesson',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='agendamiento.scheduleresource'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='agendamiento.scheduleresource'),
        ),
        migrations.AddField(
            model_name='scheduleopening',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='agendamiento.scheduleresource'),
        ),
        migrations.RunPython(create_default_resource, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='drivinglesson',
            constraint=models.UniqueConstraint(fields=('date', 'slot_key', 'resource'), name='unique_driving_lesson_by_date_slot_resource'),
        ),
        migrations.AddConstraint(
            model_name='scheduleblock',
            constraint=models.UniqueConstraint(fields=('date', 'scope', 'slot_key', 'resource'), name='unique_schedule_block_by_date_scope_slot_resource'),
        ),
        migrations.AddConstraint(
            model_name='scheduleopening',
            constraint=models.UniqueConstraint(fields=('date', 'scope', 'slot_key', 'resource'), name='unique_schedule_opening_by_date_scope_slot_resource'),
        ),
    ]
