# Generated by Django 6.0.3 on 2026-06-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0004_scheduleresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresource',
            name='color',
            field=models.CharField(default='#1f4b42', max_length=7),
        ),
    ]
